# Salmon Project
# 
# Y. Li, Dec 12 2017
# last modified Apr 10 2018

# R version -> 3.4.4 (2018-03-15)
# system -> x86_64, linux-gnu

# install.packages("INLA", repos="https://inla.r-inla-download.org/R/stable", dep=TRUE)


```{r, eval = FALSE}
rm(list=ls())
```

```{r packages and functions}
lapply(c('zoo','cowplot','nlme','MuMIn','readxl','sp','geoR','lubridate','tidyverse','INLA'),library,character.only = T)

sessionInfo()
# geoR requires XQuartz to be installed, from xquartz.macosforge.org
	
# setwd("/home/yuanheng/Documents/Project_salmon/R/")
source('source_salmon.r')
```


```{r read in data, see 'salmon_datamining.r'}
# ... 
dd.qpcr.env.adults.rm = read.table(file='data/sockeye_adults_narm_B.csv',sep=',',header=T)
# there's another file where NAs of qPCR are treated as zero ->
# file='data/sockeye_adults_nazero_B.csv'
# the plots I sent to you before are results of this dataset
```

```{r format dates}
dd.qpcr.env.adults.rm$Date = as.POSIXct(dd.qpcr.env.adults.rm$Date, format='%Y-%m-%d')
dd.qpcr.env.adults.rm$Water_Date = as.POSIXct(dd.qpcr.env.adults.rm$Water_Date, format='%Y-%m-%d')
	
dd.qpcr.env.adults.rm$txtdate = strptime(as.character(dd.qpcr.env.adults.rm$Date),'%Y-%m-%d')
dd.qpcr.env.adults.rm$txtdate = as.factor(format(dd.qpcr.env.adults.rm$txtdate,'%m-%d'))
	
datex=as.Date(strptime(dd.qpcr.env.adults.rm$txtdate,'%m-%d'))
a = c(0,int_diff(datex)/days(1))
for (i in length(a):1){	
    a[i]=sum(a[1:i]) 
    }
dd.qpcr.env.adults.rm$date.n = a
```

```{r standardize variable}
dd.qpcr.env.adults.rm$Q_corr_qpcr.rm.norm2 = MyStd(dd.qpcr.env.adults.rm$Q_corr_qpcr.rm)
	
hist(dd.qpcr.env.adults.rm$Q_corr_qpcr.rm.norm2, breaks=10)

```

```{r cut to regularly spaced time-series}
a
a[2:110]-a[1:109]
	
dd.qpcr.env.adults.rm = dd.qpcr.env.adults.rm[7:108, ]
dd.qpcr.env.adults.rm$txtdate
```

```{r explore potential independent variables}
names(dd.qpcr.env.adults.rm)
	
MyVar <- c("txtdate", "Q_corr_qpcr.rm.norm2", "Qty_ng_per_ul_mean", "Q_cfs", "SockeyeTotalCount") # date.n
	
pairs(dd.qpcr.env.adults.rm[,MyVar])
	
cor(dd.qpcr.env.adults.rm[ , c(MyVar[2:4], "date.n")])
	
corvif(dd.qpcr.env.adults.rm[ , c(MyVar[2:4], "date.n")])
	
corvif(dd.qpcr.env.adults.rm[ , c(MyVar[c(2,4)], "date.n")])
```


```{r descriptive plots}
pdf("analysis/describe_salmon.pdf", width = 15, height = 5)
par(las=1, mfrow = c(1,1), mar = c(2,5,2,.5), oma = c(1,1,1.5,1),cex=1.2)
# plot(dd.qpcr.env.adults.all$Date, dd.qpcr.env.adults.all$SockeyeTotalCount, xlab='', ylab='' ,type='l')
plot(dd.qpcr.env.adults.rm$Date, dd.qpcr.env.adults.rm$SockeyeTotalCount, xlab='', ylab='' ,type='l')
title(ylab='Individual', outer=T, line=-1.5, cex.lab=1.2)
title(main='Daily Counts', cex.main=1.5)
	
dev.off()
	
pdf("analysis/describe_qpcr.pdf", width = 15, height = 5)
par(las=1, mfrow = c(1,1), mar = c(2,5,2,.5), oma = c(1,1,1.5,1),cex=1.2)
# plot(dd.qpcr.env.adults.all$Date, dd.qpcr.env.adults.all$Q_corr_qpcr.all, xlab='', ylab='', type='l')
plot(dd.qpcr.env.adults.rm$Date, dd.qpcr.env.adults.rm$Q_corr_qpcr.rm, xlab='', ylab='', type='l')
title(ylab='flow-corrected eDNA concentration', outer=T, line=-.8, cex.lab=1.2)
title(main='Daily eDNA', cex.main=1.5)
	
dev.off()
```
	
```{r INLA models}
hist(dd.qpcr.env.adults.rm$date.n, breaks=100)
	
inla.setOption(scale.model.default = TRUE)
U = 0.1			# explore U & sigma values
hyperl=list(theta=list(prior='pc.prec', param=c(U, 0.05)))
```

	
```{r zero-inflated Poission & ar1}
# 'ar' - regularly spaced time-series
m.par0.rela = inla(SockeyeTotalCount ~ Q_corr_qpcr.rm.norm2 + f(txtdate, model = 'ar1', hyper=hyperl),
			control.compute = list(dic = T, mlik = T, cpo = T, config = T),
			control.inla = list(int.strategy = "grid", diff.logdens = 4, strategy="laplace", npoints=21),	
			control.predictor = list(compute=T),
			family = 'zeroinflatedpoisson1', # can be replaced by 'poisson'
			data = dd.qpcr.env.adults.rm
		)
	
summary(m.par0.rela)
```

	
```{r}
# no autoregression
m.pnt.rela = inla(SockeyeTotalCount ~ Q_corr_qpcr.rm.norm2,
			# verbose = T,
			control.compute = list(dic = T, config = T, mlik = T, cpo = T),
			control.inla = list(int.strategy = "grid", diff.logdens = 4, strategy = "laplace", npoints = 21),	
			control.predictor = list(compute = T),
			#control.family = list(list(prior = 'lognormal')),		# gamma
			
			family = 'zeroinflatedpoisson1', #poisson
			data = dd.qpcr.env.adults.rm
		)
	
summary(m.pnt.rela)
	
# DIC-value way too high
```


```{r model check}
#	I also tried some other model-checking criteria, but they're either too conservative (meaning all models are good according to these conservative criteria) or I'm not quite sure if I did a correct job applying them. 
#	same applies to PIT criterion, because cpo calculation failed for 32% of the data points
#	so I'm relying on the simplest ACF criterion here. 

	# PIT (probability integral transform), a form of cross-validation test 
table(m.par0.rela$cpo$failure)	# fail32% 
	
par(mfrow=c(2,1))
hist(m.par0.rela$cpo$pit, breaks=50)	# the model has bias, even though cpo fails at 32%
hist(m.par0.rela$cpo$cpo, breaks=50)	#
par(mfrow=c(1,1))	

pdf("analysis/PIT_ar-zero.pdf", width = 7, height = 7)

par(las=1, mfrow = c(1,1), mar = c(2,5,2,.5), oma = c(1,1,1,1),cex=1.2)
hist(m.par0.rela$cpo$pit,breaks=50, main="", cex.lab=1.2)
title(main='PIT-values, fail32%', cex.main=1.35)
	
dev.off()
	
#  acf (auto-correlation function), checking residual correlation
resid.count.ar0 = dd.qpcr.env.adults.rm$SockeyeTotalCount - m.par0.rela$summary.fitted.values$mean
	
pdf("analysis/acf_ar-zero.pdf", width = 7, height = 7)

par(las = 1, mfrow = c(1,1), mar = c(4,4,2.5,.5), oma = c(2,1,.5,1),cex=1.2)
acf(resid.count.ar0, type = 'correlation', main = '', cex.lab = 1.2) # covariance
title(main = 'Residual Autocorrelation', cex.main = 1.35)
# not great at the highest peak, but I would say okay

dev.off()
	
acf(resid.count.rw1, type='correlation' )
	
	# for other models 
resid.count.nt = dd.qpcr.env.adults.rm$SockeyeTotalCount - m.pnt.rela$summary.fitted.values$mean
acf(resid.count.nt,type='correlation' )
```

```{r plot model parameters with autoregression}
# ... plot latent
pdf("analysis/time-smoother_ar-zero.pdf", width = 10, height = 7)

par(las=1, mfrow = c(1,1), mar = c(4,3,2.5,.5), oma = c(1,1,1,1), cex=1.2)
plot(dd.qpcr.env.adults.rm$Date, m.par0.rela$summary.random$txtdate[,2][7:108], type = 'l', ylab = '', xlab = '', ylim = c(min(m.par0.rela$summary.random$txtdate[,4]), max(m.par0.rela$summary.random$txtdate[,6])))		#
	
title(ylab = 'smoother', outer = T, line = -1.4, cex.lab = 1.2)
title(main = 'Time Autoregression', cex.main = 1.5)
	
lines(dd.qpcr.env.adults.rm$Date, m.par0.rela$summary.random$txtdate[,4][7:108], lty = 2, col = 'black')
lines(dd.qpcr.env.adults.rm$Date, m.par0.rela$summary.random$txtdate[,6][7:108], lty = 2, col = 'black')
abline(h = 0, lty = 3)
	
dev.off()
	

# .. plot fitted with autoregression m.par0.rela
pdf("analysis/fitted_ar-zero.pdf", width = 15, height = 5)

par(las=1, mfrow = c(1,1), mar = c(4,4,2,.5), oma = c(1,1,1,1),cex=1.2)
	
plot(dd.qpcr.env.adults.rm$Date, m.par0.rela$summary.fitted.values[,"mean"], type='n', lty=1, pch=4,col='blue', ylim=c(min(m.par0.rela$summary.fitted.values[,3]),max(m.par0.rela$summary.fitted.values[,5])), xlab='', ylab='')	#, 
title(ylab='Individual', outer=T, line=-1.2, cex.lab=1.2)
title(main='Model fit', cex.main=1.5)
	
# But we also may not want an opaque polygon
polygon.x <- c(dd.qpcr.env.adults.rm$Date, rev(dd.qpcr.env.adults.rm$Date))
polygon.y <- c(m.par0.rela$summary.fitted.values$'0.025quant', rev(m.par0.rela$summary.fitted.values$'0.975quant'))
polygon(x = polygon.x, y = polygon.y, col = 'lightblue', border = NA)
	
lines(dd.qpcr.env.adults.rm$Date, m.par0.rela$summary.fitted.values[,"mean"], lty = 1,col = 'blue')
	
points(dd.qpcr.env.adults.rm$Date, dd.qpcr.env.adults.rm$SockeyeTotalCount, ylab = 'Total count',xlab = 'Date', type = 'p', pch = 20, col = '#FFA50088', lty=1)	#lwd=3, 
	
legend('topright', legend=c('count', 'fitted', '95% CI'), pch = c(20,NA, NA), col = c('#FFA50088', 'blue', 'lightblue'), lty = c(NA, 1, 1), lwd = c(1,1,10), bty = 'n', cex = 1.2)
	
dev.off()

```

```{r plot model parameters without autoregression}

# .. plot fitted without autoregression:  m.pnt.rela
pdf("analysis/fitted_ar-zero_no_autoregression.pdf", width = 15, height = 5)

par(las=1, mfrow = c(1,1), mar = c(4,4,2,.5), oma = c(1,1,1,1),cex=1.2)
	
plot(dd.qpcr.env.adults.rm$Date, m.pnt.rela$summary.fitted.values[,"mean"], type='n', lty=1, pch=4,col='blue', ylim=c(min(m.pnt.rela$summary.fitted.values[,3]),max(m.pnt.rela$summary.fitted.values[,5])), xlab='', ylab='')	#, 
title(ylab='Individual', outer=T, line=-1.2, cex.lab=1.2)
title(main='Model fit', cex.main=1.5)
	
# But we also may not want an opaque polygon
polygon.x <- c(dd.qpcr.env.adults.rm$Date, rev(dd.qpcr.env.adults.rm$Date))
polygon.y <- c(m.pnt.rela$summary.fitted.values$'0.025quant', rev(m.pnt.rela$summary.fitted.values$'0.975quant'))
polygon(x = polygon.x, y = polygon.y, col = 'lightblue', border = NA)
	
lines(dd.qpcr.env.adults.rm$Date, m.pnt.rela$summary.fitted.values[,"mean"], lty = 1,col = 'blue')
	
points(dd.qpcr.env.adults.rm$Date, dd.qpcr.env.adults.rm$SockeyeTotalCount, ylab = 'Total count',xlab = 'Date', type = 'p', pch = 20, col = '#FFA50088', lty=1)	#lwd=3, 
	
legend('topright', legend=c('count', 'fitted', '95% CI'), pch = c(20,NA, NA), col = c('#FFA50088', 'blue', 'lightblue'), lty = c(NA, 1, 1), lwd = c(1,1,10), bty = 'n', cex = 1.2)
	
dev.off()
	
	
# ... posterior distribution
pdf("analysis/posterior_ar-zero_no_autoregression.pdf", width = 12, height = 6)

par(las=1, mfrow = c(1,2), mar = c(4,4,1.5,.5), oma = c(1,1,1,1),cex=1.1)
	
aa = sd(dd.qpcr.env.adults.rm$Q_corr_qpcr.rm)
bb = mean(dd.qpcr.env.adults.rm$Q_corr_qpcr.rm)
	
plot(m.pnt.rela$marginals.fixed$"(Intercept)",type='l', xlab='Intercept', ylab='', cex.lab=1.2)
abline(v = m.pnt.rela$summary.fixed['(Intercept)', "0.5quant"], col = "red",lty=3)
abline(v = m.pnt.rela$summary.fixed['(Intercept)', "0.025quant"], col = "red",lty=3)
abline(v = m.pnt.rela$summary.fixed['(Intercept)', "0.975quant"], col = "red",lty=3)
plot(m.pnt.rela$marginals.fixed$"Q_corr_qpcr.rm.norm2"[,1]*aa + bb, m.pnt.rela$marginals.fixed$"Q_corr_qpcr.rm.norm2"[,2],type='l', xlab='eDNA concentration', ylab='', cex.lab=1.2)
	
abline(v = m.pnt.rela$summary.fixed['Q_corr_qpcr.rm.norm2', "0.5quant"]*aa + bb, col = "red",lty=3)
abline(v = m.pnt.rela$summary.fixed['Q_corr_qpcr.rm.norm2', "0.025quant"]*aa + bb, col = "red",lty=3)
abline(v = m.pnt.rela$summary.fixed['Q_corr_qpcr.rm.norm2', "0.975quant"]*aa + bb, col = "red",lty=3)
	
dev.off()
```
















